# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FFEuoQt6gsk4JqhmIVoqjhr7BvkNgBDi
"""

!pip install  streamlit
import streamlit as st
import pandas as pd
import joblib

# Load your trained model
model = joblib.load('mljar.pkl')
# Function to get user inputs and make predictions
def predict_quality(fixed_acidity, volatile_acidity, citric_acid, residual_sugar, chlorides, free_sulfur_dioxide, total_sulfur_dioxide, density, pH, sulphates, alcohol):
    features = [[fixed_acidity, volatile_acidity, citric_acid, residual_sugar, chlorides, free_sulfur_dioxide, total_sulfur_dioxide, density, pH, sulphates, alcohol]]
    quality = model.predict(features)
    return quality[0]

# Create a Streamlit web app
st.title('Wine Quality Predictor')

# Add input fields for the user
fixed_acidity = st.number_input('Fixed Acidity')
volatile_acidity = st.number_input('Volatile Acidity')
citric_acid = st.number_input('Citric Acid')
residual_sugar = st.number_input('Residual Sugar')
chlorides = st.number_input('Chlorides')
free_sulfur_dioxide = st.number_input('Free Sulfur Dioxide')
total_sulfur_dioxide = st.number_input('Total Sulfur Dioxide')
density = st.number_input('Density')
pH = st.number_input('pH')
sulphates = st.number_input('Sulphates')
alcohol = st.number_input('Alcohol')

# Make prediction when the user clicks the button
if st.button('Predict'):
    prediction = predict_quality(fixed_acidity, volatile_acidity, citric_acid, residual_sugar, chlorides, free_sulfur_dioxide, total_sulfur_dioxide, density, pH, sulphates, alcohol)
    st.write('Predicted Quality:', prediction)



